<?php 
$shippings = $this->getShippings();
require_once 'View/html/header.phtml'; 
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Manage Shipping Method</title>
    <link rel="stylesheet" type="text/css" href="skin/css/grid.css">
</head>
<body>
    <div class="head_container">
        <h2 class="logo">MANAGE SHIPPING METHOD</h2>
        <a class="add_btn" href="index.php?c=ShippingMethod&a=add">ADD SHIPPING</a>
    </div>
    <div class="tabel_container">
        <table >
            <tr>
                <th>Shipping ID</th>
                <th>Name</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>EDIT</th>
                <th>DELETE</th>
            </tr>
            <?php 
            foreach ($shippings as $shipping){
            ?>
            <tr>
                <td><?php echo $shipping["shipping_method_id"] ?></td>
                <td><?php echo $shipping["name"] ?></td>
                <td><?php echo $shipping["amount"] ?></td>
                <td>
                <?php   
                if ($shipping["status"] === 'active') {
                    echo "Active";
                }else{
                    echo "Inactive";
                }
                ?>    
                </td>
                <td><?php echo $shipping["created_at"] ?></td>
                <td><?php echo $shipping["updated_at"] ?></td>
                <td><a style="text-decoration:none;" href="index.php?c=shippingmethod&a=edit&shippingmethod_id=<?php echo $shipping["shipping_method_id"] ?>">Edit</a></td>
                <td><a style="text-decoration:none;" href="index.php?c=shippingmethod&a=delete&shippingmethod_id=<?php echo $shipping["shipping_method_id"] ?>">Delete</a></td>
            </tr>
            <?php    
            }
            ?>
        </table>
    </div>
	<div>
        <?php require_once 'View/html/footer.phtml'; ?>
    </div>
</body>
</html>