<?php
$payment = $this->getPayments();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Edit Payment Method</title>
	<link rel="stylesheet" type="text/css" href="skin/css/edit.css">
</head>
<body>
	<form method="POST" action="index.php?c=paymentmethod&a=update&payment_method_id=<?php echo $payment['payment_method_id'] ?>">
		<div class="head_container">
			<h2 class="edit_heading">EDIT PAYMENT METHOD</h2>
			<a class="cancel_link" type="cancel" href="index.php?c=payment&a=grid">CANCEL</a>
			<input class="save_link" type="submit" value="Save">
		</div>
		<div class="tabel_container">
			<table>
				<tr>
					<th>PAYMENT INFORMATION</th>
				</tr>
				<tr>
					<td>Name</td>
					<td> <input type="text" name="payment_method[name]" value=<?php echo $payment['name'] ?>> </td>
				</tr>
				<tr>
					<td>Status</td>
					<td>
						<select name="payment_method[status]">
							<option value="active" <?php if($payment['status'] == "active") echo "SELECTED";?>>Active</option>
							<option value="inactive" <?php if($payment['status'] == "inactive") echo "SELECTED";?>>Inactive</option>
						</select>
					</td>
				</tr>
			</table>
		</div>
	</form>
</body>
</html>