<?php
$payments = $this->getPayments();
require_once 'View/html/header.phtml';
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Manage Payment Method</title>
    <link rel="stylesheet" type="text/css" href="skin/css/grid.css">
</head>
<body>
    <div class="head_container">
        <h2 class="logo">MANAGE PAYMENT</h2>
        <a class="add_btn" href="index.php?c=paymentmethod&a=add">ADD PAYMENT</a>
        <link rel="stylesheet" type="text/css" href="/skin/css/grid.css">
    </div>
    <div class="tabel_container">
        <table>
            <tr>
                <th>Payment Method ID</th>
                <th>name</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>EDIT</th>
                <th>DELETE</th>
            </tr>
            <?php 
            foreach ($payments as $payment) {
            ?>
            <tr>
                <td><?php echo $payment['payment_method_id']; ?></td>
                <td><?php echo $payment["name"] ?></td>
                <td>
                <?php   
                if ($payment['status'] === "active") {
                    echo "Active";
                }else{
                    echo "Inactive";
                }
                ?>    
                </td>
                <td><?php echo $payment["created_at"] ?></td>
                <td><?php echo $payment["updated_at"] ?></td>
                <td><a style="text-decoration:none;" href="index.php?c=paymentmethod&a=edit&paymentmethod_id=<?php echo $payment['payment_method_id']; ?>">Edit</a></td>
                <td><a style="text-decoration:none;" href="index.php?c=paymentmethod&a=delete&paymentmethod_id=<?php echo $payment['payment_method_id']; ?>">Delete</a></td>
            </tr>
            <?php
            }
            ?>
        </table>
    </div>
    <div>
        <?php require_once 'View/html/footer.phtml';?>
    </div>
</body>
</html>