<?php 
$salesmen = $this->getSalesmen();
require_once 'View/html/header.phtml'; 
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Manage Salesman</title>
	<link rel="stylesheet" type="text/css" href="skin/css/grid.css">
</head>

<body>
	<div class="head_container">
		<h2 class="logo">MANAGE SALESMEN</h2>
		<a class="add_btn" href="index.php?c=salesman&a=add">ADD SALESMAN</a>
	</div>
	<div class="tabel_container">
		<table>
  			<tr>
  				<th>Salesman ID</th>
  				<th>First Name</th>
  				<th>Last Name</th>
  				<th>E-mail</th>
  				<th>Mobile</th>
  				<th>Gender</th>
  				<th>Status</th>
  				<th>Company</th>
  				<th>Created At</th>
  				<th>Updated At</th>
  				<th>EDIT</th>
  				<th>DELETE</th>
  			</tr>
  			<?php 
			foreach ($salesmen as $salesman) {	
			?>
			<tr>
				<td><?php echo $salesman["salesman_id"] ?></td>
				<td><?php echo $salesman["first_name"] ?></td>
				<td><?php echo $salesman["last_name"] ?></td>
				<td><?php echo $salesman["email"] ?></td>
				<td><?php echo $salesman["mobile"] ?></td>
				<td><?php echo $salesman["gender"] ?></td>
				<td>
                <?php   
                if ($salesman["status"] === 'active') {
                    echo "Active";
                }else{
                    echo "Inactive";
                }
                ?>    
                </td>
                <td><?php echo $salesman["company"] ?></td>
				<td><?php echo $salesman["created_at"] ?></td>
				<td><?php echo $salesman["updated_at"] ?></td>
				<td><a style="text-decoration:none;" href="index.php?c=salesman&a=edit&salesman_id=<?php echo $salesman["salesman_id"] ?>">Edit</a></td>
				<td><a style="text-decoration:none;" href="index.php?c=salesman&a=delete&salesman_id=<?php echo $salesman["salesman_id"] ?>">Delete</a></td>
			</tr>
			<?php
			}
			?>
		</table>
	</div>
	<div>
		<?php require_once 'View/html/footer.phtml'; ?>
	</div>
</body>
</html>