<?php 
$products = $this->getProducts();
require_once 'View/html/header.phtml'; 	
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Manage Product</title>
	<link rel="stylesheet" type="text/css" href="skin/css/grid.css">
</head>
<body>
	<div>
		<div class="head_container">
			<div class="logo">	MANAGE  PRODUCTS</div>
			<a class="add_btn" href="index.php?c=product&a=add">ADD PRODUCT</a>
		</div>
		<div class="tabel_container">
			<table>
				<tr>
					<th>Product ID</th>
					<th>Name</th>
					<th>SKU ID</th>
					<th>Cost</th>
					<th>Price</th>
					<th>Quantity</th>
					<th>Description</th>
					<th>Status</th>
					<th>Color</th>
					<th>Material</th>
  					<th>Created At</th>
  					<th>Updated At</th>
					<th>EDIT</th>
					<th>DELETE</th>
				</tr>
				<?php 
				foreach ($products as $product) {	
				?>
				<tr>
					<td><?php echo $product["product_id"] ?></td>
					<td><?php echo $product["name"] ?></td>
					<td><?php echo $product["sku"] ?></td>
					<td><?php echo $product["cost"] ?></td>
					<td><?php echo $product["price"] ?></td>
					<td><?php echo $product["quantity"] ?></td>
					<td><?php echo $product["description"] ?></td>
					<td>
					<?php 
					if ($product["status"] == 'active') {
						echo "active";
					}else{
						echo "Inactive";
					}
					?>	
					</td>
					<td><?php echo $product["color"] ?></td>
					<td><?php echo $product["material"] ?></td>
					<td><?php echo $product["created_at"] ?></td>
					<td><?php echo $product["updated_at"] ?></td>
					<td><a style="text-decoration:none;" href="index.php?c=product&a=edit&product_id=<?php echo $product["product_id"] ?>">Edit</a></td>
					<td><a style="text-decoration:none;" href="index.php?c=product&a=delete&product_id=<?php echo $product["product_id"] ?>">Delete</a></td>
				</tr>
				<?php
				}
				?>
			</table>
		</div>
	</div>
	<div>
	<?php require_once 'View/html/footer.phtml'; ?>
	</div>
</body>
</html>