<?php 
$customeres = $this->getCustomeres();
require_once 'View/html/header.phtml';
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Manage Customer</title>
	<link rel="stylesheet" type="text/css" href="skin/css/grid.css">
</head>

<body>
	<div class="head_container">
		<h2 class="logo">MANAGE CUSTOMERS</h2>
		<a class="add_btn" href="index.php?c=customer&a=add">ADD CUSTOMER</a>
	</div>
	<div class="tabel_container">
		<table>
  			<tr>
  				<th>Customer ID</th>
  				<th>First Name</th>
  				<th>Last Name</th>
  				<th>E-mail</th>
  				<th>Mobile</th>
  				<th>Gender</th>
  				<th>Status</th>
  				<th>Created At</th>
  				<th>Updated At</th>
  				<th>EDIT</th>
  				<th>DELETE</th>
  			</tr>
  			<?php 
			foreach ($customeres as $customer) {	
			?>
			<tr>
				<td><?php echo $customer["customer_id"] ?></td>
				<td><?php echo $customer["first_name"] ?></td>
				<td><?php echo $customer["last_name"] ?></td>
				<td><?php echo $customer["email"] ?></td>
				<td><?php echo $customer["mobile"] ?></td>
				<td><?php echo $customer["gender"] ?></td>
				<td>
                <?php   
                if ($customer["status"] === 'active') {
                    echo "Active";
                }else{
                    echo "Inactive";
                }
                ?>    
                </td>
				<td><?php echo $customer["created_at"] ?></td>
				<td><?php echo $customer["updated_at"] ?></td>
				<td><a style="text-decoration:none;" href="index.php?c=customer&a=edit&customer_id=<?php echo $customer["customer_id"] ?>">Edit</a></td>
				<td><a style="text-decoration:none;" href="index.php?c=customer&a=delete&customer_id=<?php echo $customer["customer_id"] ?>">Delete</a></td>
			</tr>
			<?php
			}
			?>
		</table>
	</div>
	<div>
		<?php require_once 'View/html/footer.phtml'; ?>
	</div>
</body>
</html>